### ISSUE TITLE
bug:imprecise footer spacing

### ISSUE THREAD

**Issue by ShobhitPatra** [pravocodes/Hacktoberfest2024#15]
Problem : In the footer ,there should be definite spacing between the image and text content
Solution : can be easily solved by adjusting the style.css
![Untitled design](https://github.com/user-attachments/assets/30cff9db-5868-4de0-9fa9-408bd96707bd)

**Comment by ShobhitPatra** [comment]
#16  fixes the issue

**Comment by pravocodes** [comment]
Hi @ShobhitPatra  It is merged under hacktoberfest.
