### ISSUE TITLE
wanna add 2d array questions c++

### ISSUE THREAD

**Issue by rahul-chakradhari** [pravocodes/Hacktoberfest2024#18]
wanna add more questions @pravocodes

**Comment by pravocodes** [comment]
what type of questions? @rahul-chakradhari

**Comment by pravocodes** [comment]
if u want to add something then raise PR.

**Comment by rahul-chakradhari** [comment]
ok but provide me proper labels requuired

**Comment by pravocodes** [comment]
Raise the PR I will add label to your PR.

**Comment by rahul-chakradhari** [comment]
sure
