### ISSUE TITLE
adding Kadane's Algorithm in cpp

### ISSUE THREAD

**Issue by Ankitmohanty2** [pravocodes/Hacktoberfest2024#20]
will you assign me this i want to work on this thorught hacktoberfest2024

**Comment by pravocodes** [comment]
Raise the PR I will label that PR as hacktoberfest.

**Comment by Coder-Madaan** [comment]
Interested in working on this part.
Can you assign it to me.

**Comment by pravocodes** [comment]
Raise the PR I will label that PR as hacktoberfest.
