### ISSUE TITLE
Add C++ File with 10 Sorting Algorithms

### ISSUE THREAD

**Issue by KartikMouli** [pravocodes/Hacktoberfest2024#21]
Hi @pravocodes , I’d like to contribute a C++ file with 10 sorting algorithms, as the project currently lacks a C++ implementation.
The sorting algorithms I’ll include are:

Bubble Sort
Selection Sort
Insertion Sort
Merge Sort
Quick Sort
Heap Sort
Radix Sort
Counting Sort
Shell Sort
Bucket Sort

Kindly assign this issue to me and add the Hacktoberfest label.

**Comment by pravocodes** [comment]
Hi @KartikMouli You add and raise the PR. I will assign that PR to hacktoberfest.
