### ISSUE TITLE
improve readme, add steps of contribution etc

### ISSUE THREAD

**Issue by kanikaa-3018** [pravocodes/Hacktoberfest2024#3]
please assign me this task for hacktoberfest24, i can further add more sorting algos like quick sort, merge sort etc

**Comment by pravocodes** [comment]
Hi @kanikaa-3018, I have assigned you this issue with the tag hacktoberfest.

**Comment by kanikaa-3018** [comment]
thankyou sir, i send the pr asap

**Comment by Astordnomer** [comment]
ha can you assign me this task

**Comment by pravocodes** [comment]
Hi @Astordnomer this issue is going to be close you can raise a new issue or directly raise the PR.
