### ISSUE TITLE
UPDATION IN README.md file required

### ISSUE THREAD

**Issue by soham0028** [pravocodes/Hacktoberfest2024#60]
hello @pravocodes 
The current readme file does not contain :
1. featured in section 
2. contributors section
3. forkers section 
4. stargazers section 
5. back to top button for easy navigation

Kindly assign me the issue with hacktoberfest labels so my work counts 
Thankyou .

**Comment by pravocodes** [comment]
Sure Raise the PR.

**Comment by eeshan15** [comment]
Hi @soham0028 How can I contribute in Hacktober fest ? I am good at python so please help me
